org: nxjuliencapellari
app: sls-tf-stack
service: sls-tf-stack
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-3
  deploymentMethod: direct

  tracing:
    lambda: true
    apiGateway: true

  environment:
#    FRONTEND_URL: ${ssm:/sls-tf-stack/${sls:stage}/frontend-url}
    TODO_TABLE: ${ssm:/sls-tf-stack/${sls:stage}/todo-table}

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
        - ${ssm:/sls-tf-stack/${sls:stage}/frontend-url}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource:
            - arn:aws:dynamodb:eu-west-3:235403126921:table/todo-sls-tf-stack-dev

  tags:
    Project: sls-tf-stack

  stackTags:
    Project: sls-tf-stack

functions:
  todos-api:
    handler: src/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}
